name: nova_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/characters/daughter_9.jpg
    - assets/images/characters/daughter_7.jpg
    - assets/images/characters/teds.jpg
    - assets/images/characters/cat1.jpg
    - assets/images/characters/cat1.png
    - assets/images/characters/cat2.png
    - assets/images/characters/daughter_7.png
    - assets/images/characters/daughter_9.png
    - assets/images/characters/teds.png
    - assets/images/characters/cat1.png
    - assets/images/characters/cat2.png
    - assets/images/characters/daughter_7.png
    - assets/images/characters/daughter_9.png
    - assets/images/characters/teds.png
    - assets/images/characters/cat2.jpg
    - assets/images/characters/dad_giraffe.jpg
    - assets/images/characters/son_giraffe_1.jpg
    - assets/images/characters/son_giraffe_2.jpg
    - assets/images/characters/jack_russell.jpg


    - assets/images/characters/dad_giraffe.png
    - assets/images/characters/son_giraffe_1.png
    - assets/images/characters/son_giraffe_2.png
    - assets/images/characters/jack_russell.png
    - assets/images/characters/daughter_7.png
    - assets/images/characters/daughter_9.png
    - assets/images/characters/teds.png
    - assets/images/characters/cat1.png
    - assets/images/characters/cat2.png
